
spring:
#  config:
#    activate:
#      on-profile: default
#  h2.console:
#    path: '/console'
  datasource:
    url: ${databaseUrl}
    username: ${username}
    password: ${password}
    platform: postgre
    driverClassName: 'org.postgresql.Driver'
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher